# NumPy Basics for Behavioral and Experimental Data

In [1]:
import numpy as np

In [2]:
# Creating an array|
a1 = np.array([1,2,3], dtype = np.int32)
print(a1)
print("dtype: ", a1.dtype)

[1 2 3]
dtype:  int32


In [3]:
# Element-wise operations
a1_2 = a1 * 2
a1_3 = a1 * np.array([2,0,0])
print(a1_2, a1_3)

[2 4 6] [2 0 0]


In [4]:
# 2D Arrays
a2 = np.array([[1,2,3],
            [4,5,6]])
print("Shape: ", a2.shape)
print("Reshaped a2:\n", a2.reshape(3,2))
print("a2:\n", a2) # reshape does not change the main array.
print("dtype: ", a2.dtype)

Shape:  (2, 3)
Reshaped a2:
 [[1 2]
 [3 4]
 [5 6]]
a2:
 [[1 2 3]
 [4 5 6]]
dtype:  int64


In [5]:
# Change dtype
a2.dtype = np.float64
print("a2 dtype after change: ", a2.dtype)

a2 dtype after change:  float64


In [6]:
# Array dimensions
print("Length:", len(a2.shape))
print("Dimensions:", a2.ndim)

Length: 2
Dimensions: 2


In [7]:
# Special arrays
a3 = np.zeros((3, 4))
print("Zero array:\n", a3)

a4 = np.linspace(0, 1, 11)
print("Linearly spaced array: ", a4)
print("Length: ", len(a4))

Zero array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Linearly spaced array:  [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
Length:  11


In [8]:
# Array info
print("a1 info:", a1.dtype, a1.shape, a1.ndim, a1.size)
print("a2 info:", a2.dtype, a2.shape, a2.ndim, a2.size)

a1 info: int32 (3,) 1 3
a2 info: float64 (2, 3) 2 6


In [9]:
# Type conversion
a5 = np.array([1,2,3], dtype = np.float32)
print("a5 dtype: ", a5.dtype)

a6 = np.array([1.7, 2.9, 3.1]).astype(np.int32)
print("a5 dtype: ", a6.dtype)

a5 dtype:  float32
a5 dtype:  int32


### Why Arrays Matter for Measurement

Arrays allow us to represent **numerical data in a structured, memory-efficient way**.  
Unlike lists, arrays are homogeneous and support **vectorized operations**, which makes it possible to:

- Perform calculations on entire datasets without loops.
- Efficiently store large numerical measurements.
- Apply mathematical and statistical operations consistently.

This is critical in scientific research, where we handle large measurements and require speed, precision, and reproducibility.


In [10]:
# Python lists vs NumPy arrays
lst_1d = [1, 2, 3, 4]
lst_2d = [[1, 2, 3],
          [4, 5, 6]]

# Convert lists to NumPy arrays
arr_1d = np.array(lst_1d)
arr_2d = np.array(lst_2d)

# Check type
print(type(arr_1d))
print(type(arr_2d))

# Check shape
print(arr_1d.shape)   # (4,)
print(arr_2d.shape)   # (2, 3)

# Check dtype
print(arr_1d.dtype)
print(arr_2d.dtype)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(4,)
(2, 3)
int64
int64


In [11]:
# Broadcasting examples
a7 = np.array([9,8,7])
a8 = np.array([[1,2,3],
              [4,5,6]])
print("1D*2D: ", a7*a8)
print("2D*1D: ", a8*a7)

1D*2D:  [[ 9 16 21]
 [36 40 42]]
2D*1D:  [[ 9 16 21]
 [36 40 42]]


In [12]:
# 2D arrays must match shape to multiply
a9 = np.array ([[1,2,3],
                [4,5,6],
                [7,8,9]])
# print("2D*3D: ", a8*a9) will result in error.

In [13]:
# 3D arrays
a10 = np.array([
    [[1,2,3], [1,2,3]], 
    [[1,2,3],[1,2,3]]
])
print(a10.dtype, a10.shape, a10.ndim, a10.size)

int64 (2, 2, 3) 3 12


Broadcasting example with compatible shapes

In [14]:
a10*a8
# a10*a9 will result in error.

array([[[ 1,  4,  9],
        [ 4, 10, 18]],

       [[ 1,  4,  9],
        [ 4, 10, 18]]])

In [15]:
# Random mini-datasets
rng = np.random.default_rng(seed=1)

# Making subjects and their quantity, and their trials:
n_subjects = 10
n_trials = 10

subject_qant = rng.normal(loc=10, scale=1, size = (n_subjects, n_trials))
# In this case, rows are subjects and columns are trials.

# Making accuracy:
acc = rng.binomial(n=1,p=0.8,size = (n_subjects, n_trials))

# Then we will learn how to combine the datasets together, and build our data with stacking.
data = np.stack([subject_qant, acc], axis=2)